apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jev13mz4t-dotnet-basic 
  janus-idp.io/tekton: jev13mz4t-dotnet-basic
  backstage.io/kubernetes-id: jev13mz4t-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jev13mz4t-dotnet-basic
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml